### ISSUE TITLE
Improving the workshop content

### ISSUE THREAD

**Issue by bkamapantula** [gramexrecipes/gramex-ml-workshop#6]
- [ ] cleaner, smaller installs
- [x] add `snippets` link on the navbar
- [ ] re-purpose `report.html` elsewhere
- [ ] minimize the number of files needed. i.e., refactor and restructure.
- [x] add how to start `gramex` in `git bash` or `terminal`

**Comment by jaidevd** [comment]
@bkamapantula Item no. 3 is essentially moving the `report.html` template to index.html, right?

**Comment by bkamapantula** [comment]
yes @jaidevd

**Comment by bkamapantula** [comment]
restructuring changes via https://github.com/bkamapantula/gramex-ml-workshop/commit/490cd05173d5499e9dc59083191cfbef74818c1a
